FROM alpine:latest
USER root
LABEL maintainer="ICpEP.SE - TUPV <tupv.bscpe@tup.edu.ph>"
LABEL description="KodIt Docker image for running user programs."
LABEL version="1.0.0"

# Install supported compilers
RUN apk update
RUN apk --no-cache add g++ gcc
RUN apk --no-cache add openjdk8
